import { createContext, useState, useCallback } from "react";

const translations = {
    en: {
        // Navbar
        home: "Home",
        listings: "Listings",
        signIn: "Sign In",
        getStarted: "Get Started",
        myBookings: "My Bookings",
        signOut: "Sign Out",
        // Hero
        trustedBy: "Trusted by 50,000+ students across India",
        findYour: "Find Your",
        perfectDorm: "Perfect PG",
        nearCampus: "Near Campus",
        heroDescription: "India's smartest platform for students to discover verified PGs, hostels & flats near their college. Browse, compare, and book — all in one place.",
        searchPlaceholder: "Search by city, college, or locality...",
        search: "Search",
        popular: "Popular:",
        // Stats
        happyStudents: "Happy Students",
        verifiedListings: "Verified Listings",
        universities: "Colleges",
        avgRating: "Average Rating",
        // Featured
        featuredListings: "Featured",
        listingsSuffix: "Listings",
        handpicked: "Handpicked student-friendly properties near top Indian colleges",
        viewAll: "View All Listings",
        // How It Works 
        howItWorks: "How",
        works: "Works",
        findingHome: "Finding your perfect student home is as easy as 1-2-3",
        searchFilter: "Search & Filter",
        searchFilterDesc: "Find housing near your college with smart filters for budget, amenities, and distance.",
        tourCompare: "Tour & Compare",
        tourCompareDesc: "Browse high-quality photos, read verified reviews, and compare your top choices.",
        bookMoveIn: "Book & Move In",
        bookMoveInDesc: "Secure your spot with instant booking. Sign your agreement digitally and get ready to move in.",
        // Universities
        housingNear: "Housing Near",
        topUniversities: "Top Colleges",
        weCover: "We cover 500+ colleges across India",
        // CTA
        readyToFind: "Ready to Find Your Dream Home?",
        joinThousands: "Join thousands of students who found their perfect place with Dormify.",
        browseListings: "Browse Listings",
        createAccount: "Create Account",
        // Map
        nearbyProperties: "Nearby",
        propertiesText: "Properties",
        enableLocation: "Enable Location",
        findNearby: "Find rentals and PGs near your current location",
        locating: "Finding your location...",
        mapDescription: "Showing properties within 50km of your location. Click on markers for details.",
        // Footer
        explore: "Explore",
        browseListingsFooter: "Browse Listings",
        howItWorksFooter: "How It Works",
        pricing: "Pricing",
        studentGuide: "Student Guide",
        landlords: "Landlords",
        listProperty: "List Property",
        landlordDashboard: "Landlord Dashboard",
        verification: "Verification",
        support: "Support",
        connect: "Connect",
        copyright: "© 2026 Dormify. All rights reserved. Built for students, by students.",
        privacy: "Privacy",
        terms: "Terms",
        cookies: "Cookies",
        // Listings page
        resultsFor: "Results for",
        allListings: "All",
        searching: "Searching...",
        propertiesFound: "properties found",
        searchCity: "Search city, college...",
        allTypes: "All Types",
        apartment: "Apartment",
        studio: "Studio",
        sharedRoom: "Shared Room",
        privateRoom: "Private Room",
        dorm: "Hostel",
        house: "House",
        anyPrice: "Any Price",
        furnished: "Furnished",
        clearAll: "Clear All",
        newest: "Newest",
        priceLow: "Price: Low→High",
        priceHigh: "Price: High→Low",
        topRated: "Top Rated",
        noProperties: "No properties found",
        tryAdjusting: "Try adjusting your filters",
        clearFilters: "Clear Filters",
        // Property Detail
        backToListings: "Back to listings",
        aboutProperty: "About This Property",
        amenitiesTitle: "Amenities",
        reviewsTitle: "Reviews",
        writeReview: "Write a Review",
        shareExperience: "Share your experience...",
        submitReview: "Submit Review",
        reviewSubmitted: "Review submitted!",
        bookProperty: "Book This Property",
        moveInDate: "Move-in Date",
        moveOutDate: "Move-out Date",
        messageOptional: "Message (optional)",
        introduceSelf: "Introduce yourself...",
        requestBooking: "Request Booking",
        booking: "Booking...",
        bookingSent: "Booking request sent! ✅",
        listedBy: "Listed by",
        perMonth: "per month",
        beds: "Beds",
        bed: "Bed",
        baths: "Baths",
        bath: "Bath",
        // Card
        reviews: "reviews",
        newRating: "New",
    },
    hi: {
        home: "होम",
        listings: "लिस्टिंग",
        signIn: "साइन इन",
        getStarted: "शुरू करें",
        myBookings: "मेरी बुकिंग",
        signOut: "साइन आउट",
        trustedBy: "भारत भर में 50,000+ छात्रों द्वारा विश्वसनीय",
        findYour: "अपना",
        perfectDorm: "परफेक्ट PG",
        nearCampus: "कैंपस के पास",
        heroDescription: "छात्रों के लिए भारत का सबसे स्मार्ट प्लेटफॉर्म — वेरिफ़ाइड PG, हॉस्टल और फ्लैट खोजें।",
        searchPlaceholder: "शहर, कॉलेज, या लोकैलिटी से खोजें...",
        search: "खोजें",
        popular: "लोकप्रिय:",
        happyStudents: "खुश छात्र",
        verifiedListings: "वेरिफ़ाइड लिस्टिंग",
        universities: "कॉलेज",
        avgRating: "औसत रेटिंग",
        featuredListings: "फीचर्ड",
        listingsSuffix: "लिस्टिंग",
        handpicked: "भारत के शीर्ष कॉलेजों के पास चुनिंदा छात्र-अनुकूल प्रॉपर्टीज",
        viewAll: "सभी लिस्टिंग देखें",
        howItWorks: "कैसे",
        works: "काम करता है",
        findingHome: "अपना परफेक्ट घर ढूंढना 1-2-3 जितना आसान है",
        searchFilter: "खोजें और फ़िल्टर करें",
        searchFilterDesc: "बजट, सुविधाओं और दूरी के लिए स्मार्ट फ़िल्टर के साथ अपने कॉलेज के पास हाउसिंग खोजें।",
        tourCompare: "देखें और तुलना करें",
        tourCompareDesc: "हाई-क्वालिटी फ़ोटो देखें, वेरिफ़ाइड रिव्यू पढ़ें, और अपने टॉप विकल्पों की तुलना करें।",
        bookMoveIn: "बुक करें और शिफ़्ट हों",
        bookMoveInDesc: "इंस्टेंट बुकिंग से अपनी जगह सुरक्षित करें। डिजिटल एग्रीमेंट साइन करें।",
        housingNear: "हाउसिंग",
        topUniversities: "टॉप कॉलेजों के पास",
        weCover: "हम भारत भर में 500+ कॉलेजों को कवर करते हैं",
        readyToFind: "अपना सपनों का घर खोजने के लिए तैयार?",
        joinThousands: "Dormify के ज़रिये हज़ारों छात्रों ने अपनी परफेक्ट जगह पाई।",
        browseListings: "लिस्टिंग देखें",
        createAccount: "अकाउंट बनाएँ",
        nearbyProperties: "आस-पास की",
        propertiesText: "प्रॉपर्टीज",
        enableLocation: "लोकेशन चालू करें",
        findNearby: "अपने मौजूदा लोकेशन के पास किराये और PG खोजें",
        locating: "आपकी लोकेशन ढूंढ रहे हैं...",
        mapDescription: "आपकी लोकेशन से 50km के भीतर प्रॉपर्टीज दिखा रहे हैं।",
        explore: "एक्सप्लोर",
        browseListingsFooter: "लिस्टिंग देखें",
        howItWorksFooter: "कैसे काम करता है",
        pricing: "प्राइसिंग",
        studentGuide: "स्टूडेंट गाइड",
        landlords: "मकान मालिक",
        listProperty: "प्रॉपर्टी लिस्ट करें",
        landlordDashboard: "डैशबोर्ड",
        verification: "वेरिफिकेशन",
        support: "सपोर्ट",
        connect: "संपर्क",
        copyright: "© 2026 Dormify. सर्वाधिकार सुरक्षित। छात्रों के लिए, छात्रों द्वारा।",
        privacy: "गोपनीयता",
        terms: "शर्तें",
        cookies: "कुकीज़",
        resultsFor: "के लिए परिणाम",
        allListings: "सभी",
        searching: "खोज रहे हैं...",
        propertiesFound: "प्रॉपर्टीज मिलीं",
        searchCity: "शहर, कॉलेज खोजें...",
        allTypes: "सभी प्रकार",
        apartment: "अपार्टमेंट",
        studio: "स्टूडियो",
        sharedRoom: "शेयर्ड रूम",
        privateRoom: "प्राइवेट रूम",
        dorm: "हॉस्टल",
        house: "हाउस",
        anyPrice: "कोई भी कीमत",
        furnished: "फर्निश्ड",
        clearAll: "सब हटाएं",
        newest: "नवीनतम",
        priceLow: "कीमत: कम→ज़्यादा",
        priceHigh: "कीमत: ज़्यादा→कम",
        topRated: "टॉप रेटेड",
        noProperties: "कोई प्रॉपर्टी नहीं मिली",
        tryAdjusting: "अपने फ़िल्टर एडजस्ट करें",
        clearFilters: "फ़िल्टर हटाएं",
        backToListings: "लिस्टिंग पर वापस",
        aboutProperty: "इस प्रॉपर्टी के बारे में",
        amenitiesTitle: "सुविधाएं",
        reviewsTitle: "रिव्यू",
        writeReview: "रिव्यू लिखें",
        shareExperience: "अपना अनुभव साझा करें...",
        submitReview: "रिव्यू सबमिट करें",
        reviewSubmitted: "रिव्यू सबमिट हो गया!",
        bookProperty: "यह प्रॉपर्टी बुक करें",
        moveInDate: "शिफ़्ट-इन तारीख",
        moveOutDate: "शिफ़्ट-आउट तारीख",
        messageOptional: "संदेश (वैकल्पिक)",
        introduceSelf: "अपना परिचय दें...",
        requestBooking: "बुकिंग रिक्वेस्ट",
        booking: "बुकिंग...",
        bookingSent: "बुकिंग रिक्वेस्ट भेजा गया! ✅",
        listedBy: "मकान मालिक",
        perMonth: "प्रति माह",
        beds: "बेड",
        bed: "बेड",
        baths: "बाथ",
        bath: "बाथ",
        reviews: "रिव्यू",
        newRating: "नया",
    },
    ta: {
        home: "முகப்பு",
        listings: "பட்டியல்",
        signIn: "உள்நுழை",
        getStarted: "தொடங்குங்கள்",
        myBookings: "என் முன்பதிவுகள்",
        signOut: "வெளியேறு",
        trustedBy: "இந்தியா முழுவதும் 50,000+ மாணவர்கள் நம்புகிறார்கள்", 
        findYour: "உங்கள்",
        perfectDorm: "சிறந்த PG",
        nearCampus: "கல்லூரி அருகில்",
        heroDescription: "கல்லூரி அருகில் PG, விடுதி & அடுக்குமாடி குடியிருப்புகளை கண்டறியுங்கள்.",
        searchPlaceholder: "நகரம், கல்லூரி தேடுங்கள்...",
        search: "தேடு",
        popular: "பிரபலமான:",
        happyStudents: "மகிழ்ச்சியான மாணவர்கள்",
        verifiedListings: "சரிபார்க்கப்பட்ட பட்டியல்",
        universities: "கல்லூரிகள்",
        avgRating: "சராசரி மதிப்பீடு",
        featuredListings: "சிறப்பு",
        listingsSuffix: "பட்டியல்",
        handpicked: "இந்தியாவின் சிறந்த கல்லூரிகள் அருகே தேர்ந்தெடுக்கப்பட்ட சொத்துக்கள்",
        viewAll: "அனைத்தையும் காண்",
        howItWorks: "எப்படி",
        works: "வேலை செய்கிறது",
        findingHome: "உங்கள் சரியான வீட்டை கண்டுபிடிப்பது 1-2-3 போல எளிது",
        searchFilter: "தேடு & வடிகட்டு",
        searchFilterDesc: "பட்ஜெட், வசதிகள் மற்றும் தூரத்திற்கான ஸ்மார்ட் வடிப்பான்களுடன் தேடுங்கள்.",
        tourCompare: "பார்வையிடு & ஒப்பிடு",
        tourCompareDesc: "புகைப்படங்களைப் பாருங்கள், விமர்சனங்களைப் படியுங்கள்.",
        bookMoveIn: "முன்பதிவு & குடியேறு",
        bookMoveInDesc: "உடனடி முன்பதிவு மூலம் உங்கள் இடத்தைப் பாதுகாக்கவும்.",
        housingNear: "குடியிருப்பு",
        topUniversities: "சிறந்த கல்லூரிகள் அருகில்",
        weCover: "இந்தியா முழுவதும் 500+ கல்லூரிகளை நாங்கள் உள்ளடக்குகிறோம்",
        readyToFind: "உங்கள் கனவு வீட்டைக் கண்டுபிடிக்க தயாரா?",
        joinThousands: "Dormify மூலம் ஆயிரக்கணக்கான மாணவர்கள் தங்கள் சிறந்த இடத்தைக் கண்டறிந்துள்ளனர்.",
        browseListings: "பட்டியலைப் பாருங்கள்",
        createAccount: "கணக்கை உருவாக்கு",
        nearbyProperties: "அருகிலுள்ள",
        propertiesText: "சொத்துக்கள்",
        enableLocation: "இருப்பிடத்தை இயக்கு",
        findNearby: "உங்கள் தற்போதைய இருப்பிடத்திற்கு அருகிலுள்ள வாடகை & PG கண்டறியுங்கள்",
        locating: "உங்கள் இருப்பிடத்தைக் கண்டறிகிறது...",
        mapDescription: "உங்கள் இருப்பிடத்திலிருந்து 50km க்குள் உள்ள சொத்துக்களைக் காட்டுகிறது.",
        explore: "ஆராயுங்கள்",
        browseListingsFooter: "பட்டியலைப் பாருங்கள்",
        howItWorksFooter: "எப்படி வேலை செய்கிறது",
        pricing: "விலை நிர்ணயம்",
        studentGuide: "மாணவர் வழிகாட்டி",
        landlords: "வீட்டு உரிமையாளர்கள்",
        listProperty: "சொத்தை பட்டியலிடு",
        landlordDashboard: "டாஷ்போர்டு",
        verification: "சரிபார்ப்பு",
        support: "ஆதரவு",
        connect: "தொடர்பு",
        copyright: "© 2026 Dormify. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
        privacy: "தனியுரிமை",
        terms: "விதிமுறைகள்",
        cookies: "குக்கீகள்",
        resultsFor: "க்கான முடிவுகள்",
        allListings: "அனைத்தும்",
        searching: "தேடுகிறது...",
        propertiesFound: "சொத்துக்கள் கிடைத்தன",
        searchCity: "நகரம், கல்லூரி தேடுங்கள்...",
        allTypes: "அனைத்து வகைகள்",
        apartment: "அடுக்குமாடி",
        studio: "ஸ்டுடியோ",
        sharedRoom: "பகிர்வு அறை",
        privateRoom: "தனி அறை",
        dorm: "விடுதி",
        house: "வீடு",
        anyPrice: "எந்த விலையும்",
        furnished: "பர்னிஷ்டு",
        clearAll: "அனைத்தையும் நீக்கு",
        newest: "புதியது",
        priceLow: "விலை: குறைவு→அதிகம்",
        priceHigh: "விலை: அதிகம்→குறைவு",
        topRated: "உயர் மதிப்பீடு",
        noProperties: "சொத்துக்கள் கிடைக்கவில்லை",
        tryAdjusting: "உங்கள் வடிப்பான்களை சரிசெய்யுங்கள்",
        clearFilters: "வடிப்பான்களை நீக்கு",
        backToListings: "பட்டியலுக்குத் திரும்பு",
        aboutProperty: "இந்த சொத்து பற்றி",
        amenitiesTitle: "வசதிகள்",
        reviewsTitle: "விமர்சனங்கள்",
        writeReview: "விமர்சனம் எழுதுங்கள்",
        shareExperience: "உங்கள் அனுபவத்தைப் பகிருங்கள்...",
        submitReview: "விமர்சனம் சமர்ப்பி",
        reviewSubmitted: "விமர்சனம் சமர்ப்பிக்கப்பட்டது!",
        bookProperty: "இந்த சொத்தை முன்பதிவு செய்",
        moveInDate: "குடியேற்ற தேதி",
        moveOutDate: "குடிவெளியேற்ற தேதி",
        messageOptional: "செய்தி (விருப்பத்தேர்வு)",
        introduceSelf: "உங்களை அறிமுகப்படுத்துங்கள்...",
        requestBooking: "முன்பதிவு கோரிக்கை",
        booking: "முன்பதிவு...",
        bookingSent: "முன்பதிவு கோரிக்கை அனுப்பப்பட்டது! ✅",
        listedBy: "பட்டியலிட்டவர்",
        perMonth: "மாதம்",
        beds: "படுக்கைகள்",
        bed: "படுக்கை",
        baths: "குளியல்",
        bath: "குளியல்",
        reviews: "விமர்சனங்கள்",
        newRating: "புதிய",
    }
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState("en");

    const t = useCallback((key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    }, [language]);

    const changeLanguage = useCallback((lang) => {
        setLanguage(lang);
    }, []);

    const languages = [
        { code: "en", label: "English", flag: "🇬🇧" },
        { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
        { code: "ta", label: "தமிழ்", flag: "🇮🇳" },
    ];

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t, languages }}>
            {children}
        </LanguageContext.Provider>
    );
}
